name: Deploy Hall of Honor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: "Fix axios {}: _global bug line"
        run: |
          echo "Looking for _global patterns:"
          grep -n "_global" node_modules/axios/lib/utils.js
          echo "Looking around line 735:"
          sed -n '730,740p' node_modules/axios/lib/utils.js
          sed -i '735d' node_modules/axios/lib/utils.js
          echo "After removing line 735:"
          sed -n '730,740p' node_modules/axios/lib/utils.js
      - name: Build project
        run: npm run build
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 42.96.40.246
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Navigate to project directory
            cd /srv/app/hall-of-honor
            # Pull latest changes
            git pull origin main
            # Install dependencies
            npm ci --legacy-peer-deps
            # Build project
            npm run build
            # Restart PM2 process
            pm2 restart hall-of-honor || pm2 start "npm run preview -- --port 5000" --name hall-of-honor
            # Save PM2 configuration
            pm2 save
            # Show status
            pm2 status
